apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: spring-demo-svc
spec:
  selector:
    app: spring-demo
  ports:
    - protocol: "TCP"
      port: 8086 # The port that the service is running on in the cluster
      targetPort: 8086 # The port exposed by the service
      nodePort: 30086
  type: NodePort # type of the service.